import type { Metadata } from "next";
import "./globals.css";
import "../../public/fonts/awesome/css/all.css";
import "../../public/fonts/iranSans/fonts.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>{children}</body>
    </html>
  );
}
